//
//  Meduman_SwiftUITests-Meduman_SwiftUIMocks.generated.swift
//  Meduman_SwiftUI
//
//  Generated by Mockingbird v0.20.0.
//  DO NOT EDIT
//

@testable import Meduman_SwiftUI
@testable import Mockingbird
import Combine
import Firebase
import FirebaseAuth
import FirebaseFirestore
import FirebaseFirestoreSwift
import Foundation
import HealthKit
import Swift
import SwiftUI
import UIKit
import XCTest

// No mocks used in 'Meduman_SwiftUITests'. Mockingbird is configured to only generate mocks for
// types that are explicitly initialized in your tests with `mock(SomeType.self)`. For more
// information, see 'Thunk Pruning' in the README.
